name: Automated PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Run PR analysis script
        run: bash ./analyze-pr.sh ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }}
